export enum AUTH_TABS {
  SIGN_IN_FORM = 'SIGN_IN_FORM',
  SIGN_UP_FORM = 'SIGN_UP_FORM',
  RECOVERY_PASSWORD_FORM = 'RECOVERY_PASSWORD_FORM',
}

export enum AUTHENTICATION {
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PROFILE = 'PROFILE',
  REFRESH = 'REFRESH',
}
