export enum RECORD {
  GET_ALL_RECORDS = 'GET_ALL_RECORDS',
  CREATE_RECORD = 'CREATE_RECORD',
}

export enum RECORD_TABS {
  CREATE_RECORD_FORM = 'CREATE_RECORD_FORM',
  CREATE_PERSON_FORM = 'CREATE_PERSON_FORM',
}

export enum RECORD_MODAL {
  RECORD_FORM_MODAL = 'RECORD_FORM_MODAL',
  RECORD_INFO_MODAL = 'RECORD_INFO_MODAL',
}

export enum RECORD_TYPES {
  MANICURE = 'MANICURE',
  PEDICURE = 'PEDICURE',
}

export enum RECORD_TYPES_VALUES {
  MANICURE = 'Маникюр',
  PEDICURE = 'Педикюр',
}

export enum RECORD_STATUS {
  FREE = 'FREE',
  BUSY = 'BUSY',
}
